name: Deploy to Production

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  production:
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: prod
    secrets: inherit
